### PR TITLE
added testDB to schema.sql and tested in sequelpro

### PR DESCRIPTION
**Pull request by kelbowelbo**

### CODE REVIEW

**Comment by kelbowelbo** [comment]
I added another commit to remove the node_modules directory, which matches the entry in .gitignore.

**Comment by wallischau** [comment]
What is the reason to remove node_modules directory? it is needed for all npm installs.

**Comment by kelbowelbo** [comment]
Hi Wallis,
If you look at our early node lessons, you’ll see that they tell us explicitly to exclude the node modules directory and include .gitignore.  Typically you don’t check the node modules into git. 
Kelly

**Comment by wallischau** [comment]
ok.  so everyone needs to run npm install everytime after doing a pull request.  Hope this works in heroku.

**Comment by kelbowelbo** [comment]
Not overtime, just the next time after this pull request.  When the repo was created, the .gitignore should have been created and installed so that we wouldn’t have to do it again. If we don’t have the .gitignore, every time we all do an add, it will add all those files again.   It will work in Heroku.

**Pull request merged**
